version: "2.2"
services:
  backend:
    build:
      context: .
      dockerfile: ocd_backend/Dockerfile.test
    image: "openstatefoundation/open-raadsinformatie-backend:${BRANCH_NAME-latest}-test"
  frontend:
    build:
      context: .
      dockerfile: ocd_frontend/Dockerfile.test
    image: "openstatefoundation/open-raadsinformatie-frontend:${BRANCH_NAME-latest}-test"
