apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: openstatefoundation/open-raadsinformatie-backend
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 5555
        envFrom:
        - configMapRef:
            name: appconfig
        volumeMounts:
        - mountPath: /opt/ori/data
          name: oridata
        - mountPath: /opt/ori/ocd_backend/sources
          name: sources
      volumes:
      - name: oridata
        persistentVolumeClaim:
          claimName: oridata
      - name: sources
        configMap:
          name: sources
